package avro

// Code generated by avro/gen. DO NOT EDIT.

// User is a generated struct.
type User struct {
	Name string `avro:"name" json:"name" yaml:"Name"`
	Age  int    `avro:"age" json:"age" yaml:"Age"`
}
